# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "bun" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "preview-src"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"      
          - "react-router"
          - "react-router-dom"
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      rxdb:
        patterns:
          - "rxdb"
          - "rxjs"
      i18next:
        patterns:
          - "i18next*"
          - "react-i18next"
          - "iso-639-1"
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    # ignore:
    #  - dependency-name: "*"
    #    update-types: ["version-update:semver-major"]

