/* repeated background images (SFG card backs) */
const Alchemists_back = new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-01.jpg", import.meta.url).href;
const Blacksmiths_back = new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-03.jpg", import.meta.url).href;
const Brewers_back = new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-03.jpg", import.meta.url).href;
const Butchers_back = new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-03.jpg", import.meta.url).href;
const Cooks_back = new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-03.jpg", import.meta.url).href;
const Engineers_back = new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-03.jpg", import.meta.url).href;
const Falconers_back = new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-03.jpg", import.meta.url).href;
const Farmers_back = new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-03.jpg", import.meta.url).href;
const Fishermen_back = new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-03.jpg", import.meta.url).href;
const Hunters_back = new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-03.jpg", import.meta.url).href;
const Masons_back = new URL("../assets/cards/Masons/GB-S4-Masons-19-08-01.jpg", import.meta.url).href;
const Miners_back = new URL("../assets/cards/Miners/GB-S4-Miners-20-03-03.jpg", import.meta.url).href;
const Morticians_back = new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-03.jpg", import.meta.url).href;
const Navigators_back = new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-03.jpg", import.meta.url).href;
const Order_back = new URL("../assets/cards/Order_back.jpg", import.meta.url).href;
const Ratcatchers_back = new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-03.jpg", import.meta.url).href;
const Shepherds_back = new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-03.jpg", import.meta.url).href;
const Union_back = new URL("../assets/cards/Union/GB-S4-Union-20-03-03.jpg", import.meta.url).href;
const Lamps_back = new URL("../assets/cards/Lamps_Backs/lamps_back_blank.jpg", import.meta.url).href;

const GBImages: Map<string, string> = new Map([
  [
    "Alchemists_back",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-19-02-01.jpg", import.meta.url).href,
  ],
  [
    "Alchemists_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-19-02-02.jpg", import.meta.url).href,
  ],
  ["Midas_back", Alchemists_back],
  [
    "Midas_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-02.jpg", import.meta.url).href,
  ],
  ["Smoke_back", Alchemists_back],
  [
    "Smoke_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-04.jpg", import.meta.url).href,
  ],
  ["Soma_back", Alchemists_back],
  [
    "Soma_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-06.jpg", import.meta.url).href,
  ],
  ["Pneuma_back", Alchemists_back],
  [
    "Pneuma_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-08.jpg", import.meta.url).href,
  ],
  ["Flask_back", Alchemists_back],
  [
    "Flask_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-10.jpg", import.meta.url).href,
  ],
  ["Naja_back", Alchemists_back],
  [
    "Naja_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-12.jpg", import.meta.url).href,
  ],
  ["Calculus_back", Alchemists_back],
  [
    "Calculus_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-14.jpg", import.meta.url).href,
  ],
  ["vCalculus_back", Alchemists_back],
  [
    "vCalculus_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-16.jpg", import.meta.url).href,
  ],
  ["Crucible_back", Alchemists_back],
  [
    "Crucible_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-18.jpg", import.meta.url).href,
  ],
  ["Kami_back", Alchemists_back],
  [
    "Kami_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-20.jpg", import.meta.url).href,
  ],
  ["Katalyst_back", Alchemists_back],
  [
    "Katalyst_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-22.jpg", import.meta.url).href,
  ],
  ["vKatalyst_back", Alchemists_back],
  [
    "vKatalyst_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-24.jpg", import.meta.url).href,
  ],
  ["Mercury_back", Alchemists_back],
  [
    "Mercury_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-26.jpg", import.meta.url).href,
  ],
  ["Venin_back", Alchemists_back],
  [
    "Venin_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-28.jpg", import.meta.url).href,
  ],
  ["Vitriol_back", Alchemists_back],
  [
    "Vitriol_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-30.jpg", import.meta.url).href,
  ],
  [
    "Compound_back",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-31.jpg", import.meta.url).href,
  ],
  [
    "Compound_front",
    new URL("../assets/cards/Alchemists/GB-S4-Alchemists-20-03-32.jpg", import.meta.url).href,
  ],
  [
    "Blacksmiths_back",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-01.jpg", import.meta.url).href,
  ],
  [
    "Blacksmiths_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-02.jpg", import.meta.url).href,
  ],
  ["Anvil_back", Blacksmiths_back],
  [
    "Anvil_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-04.jpg", import.meta.url).href,
  ],
  ["Burnish_back", Blacksmiths_back],
  [
    "Burnish_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-06.jpg", import.meta.url).href,
  ],
  ["Culverin_back", Blacksmiths_back],
  [
    "Culverin_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-08.jpg", import.meta.url).href,
  ],
  ["Farris_back", Blacksmiths_back],
  [
    "Farris_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-10.jpg", import.meta.url).href,
  ],
  ["Ferrite_back", Blacksmiths_back],
  [
    "Ferrite_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-12.jpg", import.meta.url).href,
  ],
  ["Furnace_back", Blacksmiths_back],
  [
    "Furnace_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-14.jpg", import.meta.url).href,
  ],
  ["Hearth_back", Blacksmiths_back],
  [
    "Hearth_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-16.jpg", import.meta.url).href,
  ],
  ["Alloy_back", Blacksmiths_back],
  [
    "Alloy_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-18.jpg", import.meta.url).href,
  ],
  ["Bolt_back", Blacksmiths_back],
  [
    "Bolt_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-20.jpg", import.meta.url).href,
  ],
  ["Cast_back", Blacksmiths_back],
  [
    "Cast_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-22.jpg", import.meta.url).href,
  ],
  ["Cinder_back", Blacksmiths_back],
  [
    "Cinder_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-24.jpg", import.meta.url).href,
  ],
  ["vCinder_back", Blacksmiths_back],
  [
    "vCinder_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-26.jpg", import.meta.url).href,
  ],
  ["Cutlass_back", Blacksmiths_back],
  [
    "Cutlass_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-28.jpg", import.meta.url).href,
  ],
  ["Iron_back", Blacksmiths_back],
  [
    "Iron_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-30.jpg", import.meta.url).href,
  ],
  ["Sledge_back", Blacksmiths_back],
  [
    "Sledge_front",
    new URL("../assets/cards/Blacksmiths/GB-S4-Blacksmiths-20-03-32.jpg", import.meta.url).href,
  ],
  [
    "Brewers_back",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-01.jpg", import.meta.url).href,
  ],
  [
    "Brewers_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-02.jpg", import.meta.url).href,
  ],
  ["Tapper_back", Brewers_back],
  [
    "Tapper_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-04.jpg", import.meta.url).href,
  ],
  ["Esters_back", Brewers_back],
  [
    "Esters_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-06.jpg", import.meta.url).href,
  ],
  ["Corker_back", Brewers_back],
  [
    "Corker_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-08.jpg", import.meta.url).href,
  ],
  ["Scum_back", Brewers_back],
  ["Scum_front", new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-10.jpg", import.meta.url).href],
  ["Quaff_back", Brewers_back],
  [
    "Quaff_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-12.jpg", import.meta.url).href,
  ],
  ["vDecimate_back", Brewers_back],
  [
    "vDecimate_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-14.jpg", import.meta.url).href,
  ],
  ["Flea_back", Brewers_back],
  ["Flea_front", new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-16.jpg", import.meta.url).href],
  ["Friday_back", Brewers_back],
  [
    "Friday_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-18.jpg", import.meta.url).href,
  ],
  ["Hooper_back", Brewers_back],
  [
    "Hooper_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-20.jpg", import.meta.url).href,
  ],
  ["Mash_back", Brewers_back],
  ["Mash_front", new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-22.jpg", import.meta.url).href],
  ["Pintpot_back", Brewers_back],
  [
    "Pintpot_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-24.jpg", import.meta.url).href,
  ],
  ["Spigot_back", Brewers_back],
  [
    "Spigot_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-26.jpg", import.meta.url).href,
  ],
  ["vSpigot_back", Brewers_back],
  [
    "vSpigot_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-28.jpg", import.meta.url).href,
  ],
  ["Stave_back", Brewers_back],
  [
    "Stave_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-30.jpg", import.meta.url).href,
  ],
  ["Stoker_back", Brewers_back],
  [
    "Stoker_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-32.jpg", import.meta.url).href,
  ],
  ["Lucky_back", new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-33.jpg", import.meta.url).href],
  [
    "Lucky_front",
    new URL("../assets/cards/Brewers/GB-S4-Brewers-20-03-34.jpg", import.meta.url).href,
  ],
  [
    "Butchers_back",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-01.jpg", import.meta.url).href,
  ],
  [
    "Butchers_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-02.jpg", import.meta.url).href,
  ],
  ["Ox_back", Butchers_back],
  ["Ox_front", new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-04.jpg", import.meta.url).href],
  ["Fillet_back", Butchers_back],
  [
    "Fillet_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-06.jpg", import.meta.url).href,
  ],
  ["vBoar_back", Butchers_back],
  [
    "vBoar_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-08.jpg", import.meta.url).href,
  ],
  ["Princess_back", Butchers_back],
  [
    "Princess_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-10.jpg", import.meta.url).href,
  ],
  ["Truffles_back", Butchers_back],
  [
    "Truffles_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-12.jpg", import.meta.url).href,
  ],
  ["Boar_back", Butchers_back],
  [
    "Boar_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-14.jpg", import.meta.url).href,
  ],
  ["Boiler_back", Butchers_back],
  [
    "Boiler_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-16.jpg", import.meta.url).href,
  ],
  ["Brisket_back", Butchers_back],
  [
    "Brisket_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-18.jpg", import.meta.url).href,
  ],
  ["vBrisket_back", Butchers_back],
  [
    "vBrisket_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-20.jpg", import.meta.url).href,
  ],
  ["vGutter_back", Butchers_back],
  [
    "vGutter_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-22.jpg", import.meta.url).href,
  ],
  ["Layne_back", Butchers_back],
  [
    "Layne_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-24.jpg", import.meta.url).href,
  ],
  ["Meathook_back", Butchers_back],
  [
    "Meathook_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-26.jpg", import.meta.url).href,
  ],
  ["vOx_back", Butchers_back],
  [
    "vOx_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-28.jpg", import.meta.url).href,
  ],
  ["Shank_back", Butchers_back],
  [
    "Shank_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-30.jpg", import.meta.url).href,
  ],
  ["Tenderiser_back", Butchers_back],
  [
    "Tenderiser_front",
    new URL("../assets/cards/Butchers/GB-S4-Butchers-19-08-32.jpg", import.meta.url).href,
  ],
  ["Cooks_back", new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-01.jpg", import.meta.url).href],
  ["Cooks_front", new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-02.jpg", import.meta.url).href],
  ["Wellington_back", Cooks_back],
  [
    "Wellington_front",
    new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-04.jpg", import.meta.url).href,
  ],
  ["Pepper_back", Cooks_back],
  ["Pepper_front", new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-06.jpg", import.meta.url).href],
  ["Cinnamon_back", Cooks_back],
  ["Cinnamon_front", new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-08.jpg", import.meta.url).href],
  ["Roast_back", Cooks_back],
  ["Roast_front", new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-10.jpg", import.meta.url).href],
  ["Spice_back", Cooks_back],
  ["Spice_front", new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-12.jpg", import.meta.url).href],
  ["Sugar_back", Cooks_back],
  ["Sugar_front", new URL("../assets/cards/Cooks/GB-S4-Cooks-19-08-14.jpg", import.meta.url).href],
  [
    "Engineers_back",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-01.jpg", import.meta.url).href,
  ],
  [
    "Engineers_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-02.jpg", import.meta.url).href,
  ],
  ["Ballista_back", Engineers_back],
  [
    "Ballista_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-04.jpg", import.meta.url).href,
  ],
  ["PinVice_back", Engineers_back],
  [
    "PinVice_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-06.jpg", import.meta.url).href,
  ],
  ["Rivet_back", Engineers_back],
  [
    "Rivet_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-08.jpg", import.meta.url).href,
  ],
  ["Mainspring_back", Engineers_back],
  [
    "Mainspring_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-10.jpg", import.meta.url).href,
  ],
  ["Mother_back", Engineers_back],
  [
    "Mother_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-12.jpg", import.meta.url).href,
  ],
  ["Colossus_back", Engineers_back],
  [
    "Colossus_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-14.jpg", import.meta.url).href,
  ],
  ["vHarrietTheHat_back", Engineers_back],
  [
    "vHarrietTheHat_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-16.jpg", import.meta.url).href,
  ],
  ["Hoist_back", Engineers_back],
  [
    "Hoist_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-18.jpg", import.meta.url).href,
  ],
  ["Locus_back", Engineers_back],
  [
    "Locus_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-20.jpg", import.meta.url).href,
  ],
  ["Nomad_back", Engineers_back],
  [
    "Nomad_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-22.jpg", import.meta.url).href,
  ],
  ["Ratchet_back", Engineers_back],
  [
    "Ratchet_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-24.jpg", import.meta.url).href,
  ],
  ["Salvo_back", Engineers_back],
  [
    "Salvo_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-26.jpg", import.meta.url).href,
  ],
  ["Velocity_back", Engineers_back],
  [
    "Velocity_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-28.jpg", import.meta.url).href,
  ],
  ["vVelocity_back", Engineers_back],
  [
    "vVelocity_front",
    new URL("../assets/cards/Engineers/GB-S4-Engineers-20-03-30.jpg", import.meta.url).href,
  ],
  [
    "Falconers_back",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-01.jpg", import.meta.url).href,
  ],
  [
    "Falconers_front",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-02.jpg", import.meta.url).href,
  ],
  ["Devana_back", Falconers_back],
  [
    "Devana_front",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-04.jpg", import.meta.url).href,
  ],
  ["Frelsi_back", Falconers_back],
  [
    "Frelsi_front",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-06.jpg", import.meta.url).href,
  ],
  ["Ikaros_back", Falconers_back],
  [
    "Ikaros_front",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-08.jpg", import.meta.url).href,
  ],
  ["Mataagi_back", Falconers_back],
  [
    "Mataagi_front",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-10.jpg", import.meta.url).href,
  ],
  ["Minerva_back", Falconers_back],
  [
    "Minerva_front",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-12.jpg", import.meta.url).href,
  ],
  ["Rundaas_back", Falconers_back],
  [
    "Rundaas_front",
    new URL("../assets/cards/Falconers/GB-S4-Falconers-20-03-14.jpg", import.meta.url).href,
  ],
  [
    "Farmers_back",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-01.jpg", import.meta.url).href,
  ],
  [
    "Farmers_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-02.jpg", import.meta.url).href,
  ],
  ["Grange_back", Farmers_back],
  [
    "Grange_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-04.jpg", import.meta.url).href,
  ],
  ["Thresher_back", Farmers_back],
  [
    "Thresher_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-06.jpg", import.meta.url).href,
  ],
  ["Festival_back", Farmers_back],
  [
    "Festival_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-08.jpg", import.meta.url).href,
  ],
  ["Peck_back", Farmers_back],
  ["Peck_front", new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-10.jpg", import.meta.url).href],
  ["Buckwheat_back", Farmers_back],
  [
    "Buckwheat_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-12.jpg", import.meta.url).href,
  ],
  ["Amber_back", Farmers_back],
  [
    "Amber_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-14.jpg", import.meta.url).href,
  ],
  ["Bushel_back", Farmers_back],
  [
    "Bushel_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-16.jpg", import.meta.url).href,
  ],
  ["Fallow_back", Farmers_back],
  [
    "Fallow_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-18.jpg", import.meta.url).href,
  ],
  ["Harrow_back", Farmers_back],
  [
    "Harrow_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-20.jpg", import.meta.url).href,
  ],
  ["vHonour_back", Farmers_back],
  [
    "vHonour_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-22.jpg", import.meta.url).href,
  ],
  ["Jackstraw_back", Farmers_back],
  [
    "Jackstraw_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-24.jpg", import.meta.url).href,
  ],
  ["Millstone_back", Farmers_back],
  [
    "Millstone_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-26.jpg", import.meta.url).href,
  ],
  ["Ploughman_back", Farmers_back],
  [
    "Ploughman_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-28.jpg", import.meta.url).href,
  ],
  ["Tater_back", Farmers_back],
  [
    "Tater_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-30.jpg", import.meta.url).href,
  ],
  ["Windle_back", Farmers_back],
  [
    "Windle_front",
    new URL("../assets/cards/Farmers/GB-S4-Farmers-19-12-32.jpg", import.meta.url).href,
  ],
  [
    "Fishermen_back",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-01.jpg", import.meta.url).href,
  ],
  [
    "Fishermen_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-02.jpg", import.meta.url).href,
  ],
  ["Shark_back", Fishermen_back],
  [
    "Shark_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-04.jpg", import.meta.url).href,
  ],
  ["Corsair_back", Fishermen_back],
  [
    "Corsair_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-06.jpg", import.meta.url).href,
  ],
  ["Yukai_back", Fishermen_back],
  [
    "Yukai_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-08.jpg", import.meta.url).href,
  ],
  ["Salt_back", Fishermen_back],
  [
    "Salt_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-10.jpg", import.meta.url).href,
  ],
  ["Tentacles_back", Fishermen_back],
  [
    "Tentacles_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-12.jpg", import.meta.url).href,
  ],
  ["Angel_back", Fishermen_back],
  [
    "Angel_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-14.jpg", import.meta.url).href,
  ],
  ["Greyscales_back", Fishermen_back],
  [
    "Greyscales_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-16.jpg", import.meta.url).href,
  ],
  ["Hag_back", Fishermen_back],
  [
    "Hag_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-18.jpg", import.meta.url).href,
  ],
  ["Jac_back", Fishermen_back],
  [
    "Jac_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-20.jpg", import.meta.url).href,
  ],
  ["Knuckles_back", Fishermen_back],
  [
    "Knuckles_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-22.jpg", import.meta.url).href,
  ],
  ["Kraken_back", Fishermen_back],
  [
    "Kraken_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-24.jpg", import.meta.url).href,
  ],
  ["Sakana_back", Fishermen_back],
  [
    "Sakana_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-26.jpg", import.meta.url).href,
  ],
  ["vSakana_back", Fishermen_back],
  [
    "vSakana_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-28.jpg", import.meta.url).href,
  ],
  ["Siren_back", Fishermen_back],
  [
    "Siren_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-30.jpg", import.meta.url).href,
  ],
  ["vSiren_back", Fishermen_back],
  [
    "vSiren_front",
    new URL("../assets/cards/Fishermen/GB-S4-Fishermen-19-08-32.jpg", import.meta.url).href,
  ],
  [
    "Hunters_back",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-01.jpg", import.meta.url).href,
  ],
  [
    "Hunters_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-02.jpg", import.meta.url).href,
  ],
  ["Theron_back", Hunters_back],
  [
    "Theron_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-04.jpg", import.meta.url).href,
  ],
  ["Skatha_back", Hunters_back],
  [
    "Skatha_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-06.jpg", import.meta.url).href,
  ],
  ["Steeljaw_back", Hunters_back],
  [
    "Steeljaw_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-08.jpg", import.meta.url).href,
  ],
  ["Fahad_back", Hunters_back],
  [
    "Fahad_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-10.jpg", import.meta.url).href,
  ],
  ["Snow_back", Hunters_back],
  ["Snow_front", new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-12.jpg", import.meta.url).href],
  ["Chaska_back", Hunters_back],
  [
    "Chaska_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-14.jpg", import.meta.url).href,
  ],
  ["Edge_back", Hunters_back],
  ["Edge_front", new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-16.jpg", import.meta.url).href],
  ["Egret_back", Hunters_back],
  [
    "Egret_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-18.jpg", import.meta.url).href,
  ],
  ["Hearne_back", Hunters_back],
  [
    "Hearne_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-20.jpg", import.meta.url).href,
  ],
  ["vHearne_back", Hunters_back],
  [
    "vHearne_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-22.jpg", import.meta.url).href,
  ],
  ["Jaecar_back", Hunters_back],
  [
    "Jaecar_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-24.jpg", import.meta.url).href,
  ],
  ["vMinx_back", Hunters_back],
  [
    "vMinx_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-26.jpg", import.meta.url).href,
  ],
  ["Seenah_back", Hunters_back],
  [
    "Seenah_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-28.jpg", import.meta.url).href,
  ],
  ["Ulfr_back", Hunters_back],
  ["Ulfr_front", new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-30.jpg", import.meta.url).href],
  ["Zarola_back", Hunters_back],
  [
    "Zarola_front",
    new URL("../assets/cards/Hunters/GB-S4-Hunters-19-08-32.jpg", import.meta.url).href,
  ],
  ["Masons_back", new URL("../assets/cards/Masons/GB-S4-Masons-19-03-01.jpg", import.meta.url).href],
  ["Masons_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-03-02.jpg", import.meta.url).href],
  ["Honour_back", Masons_back],
  ["Honour_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-02.jpg", import.meta.url).href],
  ["Hammer_back", Masons_back],
  ["Hammer_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-04.jpg", import.meta.url).href],
  ["Corbelli_back", Masons_back],
  [
    "Corbelli_front",
    new URL("../assets/cards/Masons/GB-S4-Masons-19-08-06.jpg", import.meta.url).href,
  ],
  ["Marbles_back", Masons_back],
  [
    "Marbles_front",
    new URL("../assets/cards/Masons/GB-S4-Masons-19-08-08.jpg", import.meta.url).href,
  ],
  ["Wrecker_back", Masons_back],
  [
    "Wrecker_front",
    new URL("../assets/cards/Masons/GB-S4-Masons-19-08-10.jpg", import.meta.url).href,
  ],
  ["Brick_back", Masons_back],
  ["Brick_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-12.jpg", import.meta.url).href],
  ["Champ_back", Masons_back],
  ["Champ_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-14.jpg", import.meta.url).href],
  ["Chisel_back", Masons_back],
  ["Chisel_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-16.jpg", import.meta.url).href],
  ["vChisel_back", Masons_back],
  [
    "vChisel_front",
    new URL("../assets/cards/Masons/GB-S4-Masons-19-08-18.jpg", import.meta.url).href,
  ],
  ["Flint_back", Masons_back],
  ["Flint_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-20.jpg", import.meta.url).href],
  ["Granite_back", Masons_back],
  [
    "Granite_front",
    new URL("../assets/cards/Masons/GB-S4-Masons-19-08-22.jpg", import.meta.url).href,
  ],
  ["Harmony_back", Masons_back],
  [
    "Harmony_front",
    new URL("../assets/cards/Masons/GB-S4-Masons-19-08-24.jpg", import.meta.url).href,
  ],
  ["vHarmony_back", Masons_back],
  [
    "vHarmony_front",
    new URL("../assets/cards/Masons/GB-S4-Masons-19-08-26.jpg", import.meta.url).href,
  ],
  ["Mallet_back", Masons_back],
  ["Mallet_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-28.jpg", import.meta.url).href],
  ["Tower_back", Masons_back],
  ["Tower_front", new URL("../assets/cards/Masons/GB-S4-Masons-19-08-30.jpg", import.meta.url).href],
  ["Miners_back", new URL("../assets/cards/Miners/GB-S4-Miners-20-03-01.jpg", import.meta.url).href],
  ["Miners_front", new URL("../assets/cards/Miners/GB-S4-Miners-20-03-02.jpg", import.meta.url).href],
  ["Shaft_back", Miners_back],
  ["Shaft_front", new URL("../assets/cards/Miners/GB-S4-Miners-20-03-04.jpg", import.meta.url).href],
  ["Digger_back", Miners_back],
  ["Digger_front", new URL("../assets/cards/Miners/GB-S4-Miners-20-03-06.jpg", import.meta.url).href],
  ["Fissure_back", Miners_back],
  [
    "Fissure_front",
    new URL("../assets/cards/Miners/GB-S4-Miners-20-03-08.jpg", import.meta.url).href,
  ],
  ["Fuse_back", Miners_back],
  ["Fuse_front", new URL("../assets/cards/Miners/GB-S4-Miners-20-03-10.jpg", import.meta.url).href],
  ["Mule_back", Miners_back],
  ["Mule_front", new URL("../assets/cards/Miners/GB-S4-Miners-20-03-12.jpg", import.meta.url).href],
  ["Spade_back", Miners_back],
  ["Spade_front", new URL("../assets/cards/Miners/GB-S4-Miners-20-03-14.jpg", import.meta.url).href],
  [
    "Morticians_back",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-01.jpg", import.meta.url).href,
  ],
  [
    "Morticians_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-02.jpg", import.meta.url).href,
  ],
  ["Obulus_back", Morticians_back],
  [
    "Obulus_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-04.jpg", import.meta.url).href,
  ],
  ["Scalpel_back", Morticians_back],
  [
    "Scalpel_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-06.jpg", import.meta.url).href,
  ],
  ["Mourn_back", Morticians_back],
  [
    "Mourn_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-08.jpg", import.meta.url).href,
  ],
  ["Dirge_back", Morticians_back],
  [
    "Dirge_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-10.jpg", import.meta.url).href,
  ],
  ["Vileswarm_back", Morticians_back],
  [
    "Vileswarm_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-12.jpg", import.meta.url).href,
  ],
  ["Bonesaw_back", Morticians_back],
  [
    "Bonesaw_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-14.jpg", import.meta.url).href,
  ],
  ["Brainpan_back", Morticians_back],
  [
    "Brainpan_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-16.jpg", import.meta.url).href,
  ],
  ["Memory_back", Morticians_back],
  [
    "Memory_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-18.jpg", import.meta.url).href,
  ],
  ["Casket_back", Morticians_back],
  [
    "Casket_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-20.jpg", import.meta.url).href,
  ],
  ["Cosset_back", Morticians_back],
  [
    "Cosset_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-22.jpg", import.meta.url).href,
  ],
  ["Gaffer_back", Morticians_back],
  [
    "Gaffer_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-24.jpg", import.meta.url).href,
  ],
  ["Ghast_back", Morticians_back],
  [
    "Ghast_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-26.jpg", import.meta.url).href,
  ],
  ["Graves_back", Morticians_back],
  [
    "Graves_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-28.jpg", import.meta.url).href,
  ],
  ["vGraves_back", Morticians_back],
  [
    "vGraves_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-30.jpg", import.meta.url).href,
  ],
  ["vHemlocke_back", Morticians_back],
  [
    "vHemlocke_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-32.jpg", import.meta.url).href,
  ],
  ["Silence_back", Morticians_back],
  [
    "Silence_front",
    new URL("../assets/cards/Morticians/GB-S4-Morticians-19-08-34.jpg", import.meta.url).href,
  ],
  [
    "Navigators_back",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-01.jpg", import.meta.url).href,
  ],
  [
    "Navigators_front",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-02.jpg", import.meta.url).href,
  ],
  ["Windfinder_back", Navigators_back],
  [
    "Wander_front",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-04.jpg", import.meta.url).href,
  ],
  [
    "Windfinder_front",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-05.jpg", import.meta.url).href,
  ],
  ["Wander_back", Navigators_back],
  [
    "Azimuth_front",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-07.jpg", import.meta.url).href,
  ],
  ["Azimuth_back", Navigators_back],
  ["Ebb_back", Navigators_back],
  [
    "Ebb_front",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-10.jpg", import.meta.url).href,
  ],
  [
    "Fathom_front",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-11.jpg", import.meta.url).href,
  ],
  ["Fathom_back", Navigators_back],
  ["Horizon_back", Navigators_back],
  [
    "Horizon_front",
    new URL("../assets/cards/Navigators/GB-S4-Navigators-20-03-14.jpg", import.meta.url).href,
  ],
  ["Order_back", new URL("../assets/cards/Order/GB-S4-Order-19-08-01.jpg", import.meta.url).href],
  ["Order_front", new URL("../assets/cards/Order/GB-S4-Order-19-08-02.jpg", import.meta.url).href],
  ["sBrisket_back", Order_back],
  ["sBrisket_front", new URL("../assets/cards/Order/GB-S4-Order-19-08-04.jpg", import.meta.url).href],
  ["Pride_back", Order_back],
  ["Pride_front", new URL("../assets/cards/Order/GB-S4-Order-19-08-06.jpg", import.meta.url).href],
  ["Benediction_back", Order_back],
  [
    "Benediction_front",
    new URL("../assets/cards/Order/GB-S4-Order-19-08-08.jpg", import.meta.url).href,
  ],
  ["vFangtooth_back", Order_back],
  [
    "vFangtooth_front",
    new URL("../assets/cards/Order/GB-S4-Order-19-08-10.jpg", import.meta.url).href,
  ],
  ["Grace_back", Order_back],
  ["Grace_front", new URL("../assets/cards/Order/GB-S4-Order-19-08-12.jpg", import.meta.url).href],
  ["HarryTheHat_back", Order_back],
  [
    "HarryTheHat_front",
    new URL("../assets/cards/Order/GB-S4-Order-19-08-14.jpg", import.meta.url).href,
  ],
  ["Mist_back", Order_back],
  ["Mist_front", new URL("../assets/cards/Order/GB-S4-Order-19-08-16.jpg", import.meta.url).href],
  ["sSpigot_back", Order_back],
  ["sSpigot_front", new URL("../assets/cards/Order/GB-S4-Order-19-08-18.jpg", import.meta.url).href],
  [
    "Ratcatchers_back",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-01.jpg", import.meta.url).href,
  ],
  [
    "Ratcatchers_front",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-02.jpg", import.meta.url).href,
  ],
  ["Piper_back", Ratcatchers_back],
  [
    "Piper_front",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-04.jpg", import.meta.url).href,
  ],
  ["Squeak_back", Ratcatchers_back],
  [
    "Squeak_front",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-06.jpg", import.meta.url).href,
  ],
  ["Miasma_back", Ratcatchers_back],
  [
    "Miasma_front",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-08.jpg", import.meta.url).href,
  ],
  ["Pelage_back", Ratcatchers_back],
  [
    "Pelage_front",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-10.jpg", import.meta.url).href,
  ],
  ["Scourge_back", Ratcatchers_back],
  [
    "Scourge_front",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-12.jpg", import.meta.url).href,
  ],
  ["Skulk_back", Ratcatchers_back],
  [
    "Skulk_front",
    new URL("../assets/cards/Ratcatchers/GB-S4-Ratcatchers-19-08-14.jpg", import.meta.url).href,
  ],
  [
    "Shepherds_back",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-01.jpg", import.meta.url).href,
  ],
  [
    "Shepherds_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-02.jpg", import.meta.url).href,
  ],
  ["Herder_back", Shepherds_back],
  [
    "Herder_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-04.jpg", import.meta.url).href,
  ],
  ["Babe_back", Shepherds_back],
  [
    "Babe_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-06.jpg", import.meta.url).href,
  ],
  ["Crook_back", Shepherds_back],
  [
    "Crook_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-08.jpg", import.meta.url).href,
  ],
  ["Hook_back", Shepherds_back],
  [
    "Hook_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-10.jpg", import.meta.url).href,
  ],
  ["Lamb_back", Shepherds_back],
  [
    "Lamb_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-12.jpg", import.meta.url).href,
  ],
  ["Ram_back", Shepherds_back],
  [
    "Ram_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-14.jpg", import.meta.url).href,
  ],
  ["Shearer_back", Shepherds_back],
  [
    "Shearer_front",
    new URL("../assets/cards/Shepherds/GB-S4-Shepherds-20-03-16.jpg", import.meta.url).href,
  ],
  ["Union_back", new URL("../assets/cards/Union/GB-S4-Union-20-03-01.jpg", import.meta.url).href],
  ["Union_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-02.jpg", import.meta.url).href],
  ["Blackheart_back", Union_back],
  [
    "Blackheart_front",
    new URL("../assets/cards/Union/GB-S4-Union-20-03-04.jpg", import.meta.url).href,
  ],
  ["vRage_back", Union_back],
  ["vRage_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-06.jpg", import.meta.url).href],
  ["vGreede_back", Union_back],
  ["vGreede_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-08.jpg", import.meta.url).href],
  ["Coin_back", Union_back],
  ["Coin_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-10.jpg", import.meta.url).href],
  ["Strongbox_back", Union_back],
  [
    "Strongbox_front",
    new URL("../assets/cards/Union/GB-S4-Union-20-03-12.jpg", import.meta.url).href,
  ],
  ["Avarisse_back", Union_back],
  ["Avarisse_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-14.jpg", import.meta.url).href],
  ["Greede_back", Union_back],
  ["Greede_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-16.jpg", import.meta.url).href],
  ["Decimate_back", Union_back],
  ["Decimate_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-18.jpg", import.meta.url).href],
  ["Fangtooth_back", Union_back],
  [
    "Fangtooth_front",
    new URL("../assets/cards/Union/GB-S4-Union-20-03-20.jpg", import.meta.url).href,
  ],
  ["Gutter_back", Union_back],
  ["Gutter_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-22.jpg", import.meta.url).href],
  ["Hemlocke_back", Union_back],
  ["Hemlocke_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-24.jpg", import.meta.url).href],
  ["Minx_back", Union_back],
  ["Minx_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-26.jpg", import.meta.url).href],
  ["Rage_back", Union_back],
  ["Rage_front", new URL("../assets/cards/Union/GB-S4-Union-20-03-28.jpg", import.meta.url).href],
  ["Snakeskin_back", Union_back],
  [
    "Snakeskin_front",
    new URL("../assets/cards/Union/GB-S4-Union-20-03-30.jpg", import.meta.url).href,
  ],
  ["Lamplighters_front", new URL("../assets/cards/Lamplighters/lamp-beta.png", import.meta.url).href],
  ["Lamplighters_back", new URL("../assets/cards/Lamplighters/lamp-beta.png", import.meta.url).href],
  // [
  //   "Nightlight_front",
  //   new URL("../assets/cards/Lamplighters/nightlight-00.jpg", import.meta.url).href,
  // ],
  // [
  //   "Nightlight_back",
  //   new URL("../assets/cards/Lamplighters/nightlight-01.jpg", import.meta.url).href,
  // ],
  // ["Soot_front", new URL("../assets/cards/Lamplighters/soot-00.jpg", import.meta.url).href],
  // ["Soot_back", new URL("../assets/cards/Lamplighters/soot-01.jpg", import.meta.url).href],
  // ["Beacon_front", new URL("../assets/cards/Lamplighters/beacon-00.jpg", import.meta.url).href],
  // ["Beacon_back", new URL("../assets/cards/Lamplighters/beacon-01.jpg", import.meta.url).href],
  // ["Heat_front", new URL("../assets/cards/Lamplighters/heat-00.jpg", import.meta.url).href],
  // ["Heat_back", new URL("../assets/cards/Lamplighters/heat-01.jpg", import.meta.url).href],
  // ["Phosphor_front", new URL("../assets/cards/Lamplighters/phosphor-00.jpg", import.meta.url).href],
  // ["Phosphor_back", new URL("../assets/cards/Lamplighters/phosphor-01.jpg", import.meta.url).href],
  // ["Wick_front", new URL("../assets/cards/Lamplighters/wick-00.jpg", import.meta.url).href],
  // ["Wick_back", new URL("../assets/cards/Lamplighters/wick-01.jpg", import.meta.url).href],
  /* Lamplighters full card */
  ["Nightlight_full", new URL("../assets/cards/Lamplighters/nightlight_full.jpg", import.meta.url).href],
  ["Soot_full", new URL("../assets/cards/Lamplighters/soot_full.jpg", import.meta.url).href],
  ["Beacon_full", new URL("../assets/cards/Lamplighters/beacon_full.jpg", import.meta.url).href],
  ["Heat_full", new URL("../assets/cards/Lamplighters/heat_full.jpg", import.meta.url).href],
  ["Phosphor_full", new URL("../assets/cards/Lamplighters/phosphor_full.jpg", import.meta.url).href],
  ["Wick_full", new URL("../assets/cards/Lamplighters/wick_full.jpg", import.meta.url).href],
  /* GBCP 4.4 Errata Images */
  ["sBrisket_gbcp_front", new URL("../assets/cards/GBCP/brisket3-00.jpg", import.meta.url).href],
  ["sBrisket_gbcp_back", new URL("../assets/cards/GBCP/brisket3-01.jpg", import.meta.url).href],
  ["Cast_gbcp_front", new URL("../assets/cards/GBCP/cast-00.jpg", import.meta.url).href],
  ["Cast_gbcp_back", new URL("../assets/cards/GBCP/cast-01.jpg", import.meta.url).href],
  ["Crook_gbcp_front", new URL("../assets/cards/GBCP/crook-00.jpg", import.meta.url).href],
  ["Crook_gbcp_back", new URL("../assets/cards/GBCP/crook-01.jpg", import.meta.url).href],
  ["Egret_gbcp_front", new URL("../assets/cards/GBCP/egret-00.jpg", import.meta.url).href],
  ["Egret_gbcp_back", new URL("../assets/cards/GBCP/egret-01.jpg", import.meta.url).href],
  ["Hook_gbcp_front", new URL("../assets/cards/GBCP/hook-00.jpg", import.meta.url).href],
  ["Hook_gbcp_back", new URL("../assets/cards/GBCP/hook-01.jpg", import.meta.url).href],
  ["Ikaros_gbcp_front", new URL("../assets/cards/GBCP/ikaros-00.jpg", import.meta.url).href],
  ["Ikaros_gbcp_back", new URL("../assets/cards/GBCP/ikaros-01.jpg", import.meta.url).href],
  ["Lucky_gbcp_front", new URL("../assets/cards/GBCP/lucky-00.jpg", import.meta.url).href],
  ["Lucky_gbcp_back", new URL("../assets/cards/GBCP/lucky-01.jpg", import.meta.url).href],
  ["Miasma_gbcp_front", new URL("../assets/cards/GBCP/miasma-00.jpg", import.meta.url).href],
  ["Miasma_gbcp_back", new URL("../assets/cards/GBCP/miasma-01.jpg", import.meta.url).href],
  ["Minx_gbcp_front", new URL("../assets/cards/GBCP/minx-00.jpg", import.meta.url).href],
  ["Minx_gbcp_back", new URL("../assets/cards/GBCP/minx-01.jpg", import.meta.url).href],
  ["Steeljaw_gbcp_front", new URL("../assets/cards/GBCP/steeljaw-00.jpg", import.meta.url).href],
  ["Steeljaw_gbcp_back", new URL("../assets/cards/GBCP/steeljaw-01.jpg", import.meta.url).href],
  ["Tenderiser_gbcp_front", new URL("../assets/cards/GBCP/tenderiser-00.jpg", import.meta.url).href],
  ["Tenderiser_gbcp_back", new URL("../assets/cards/GBCP/tenderiser-01.jpg", import.meta.url).href],
  /* GBCP 4.5 Errata Images */
  ["Angel_gbcp_front", new URL("../assets/cards/GBCP/Angel-00.jpg", import.meta.url).href],
  ["Angel_gbcp_back", new URL("../assets/cards/GBCP/Angel-01.jpg", import.meta.url).href],
  ["Blackheart_gbcp_front", new URL("../assets/cards/GBCP/Blackheart-00.jpg", import.meta.url).href],
  ["Blackheart_gbcp_back", new URL("../assets/cards/GBCP/Blackheart-01.jpg", import.meta.url).href],
  ["Brisket_gbcp_front", new URL("../assets/cards/GBCP/Brisket-00.jpg", import.meta.url).href],
  ["Brisket_gbcp_back", new URL("../assets/cards/GBCP/Brisket-01.jpg", import.meta.url).href],
  ["Flea_gbcp_front", new URL("../assets/cards/GBCP/Flea-00.jpg", import.meta.url).href],
  ["Flea_gbcp_back", new URL("../assets/cards/GBCP/Flea-01.jpg", import.meta.url).href],
  ["Gaffer_gbcp_front", new URL("../assets/cards/GBCP/Gaffer-00.jpg", import.meta.url).href],
  ["Gaffer_gbcp_back", new URL("../assets/cards/GBCP/Gaffer-01.jpg", import.meta.url).href],
  ["Locus_gbcp_front", new URL("../assets/cards/GBCP/Locus-00.jpg", import.meta.url).href],
  ["Locus_gbcp_back", new URL("../assets/cards/GBCP/Locus-01.jpg", import.meta.url).href],
  ["Salt_gbcp_front", new URL("../assets/cards/GBCP/Salt-00.jpg", import.meta.url).href],
  ["Salt_gbcp_back", new URL("../assets/cards/GBCP/Salt-01.jpg", import.meta.url).href],
  ["Truffles_gbcp_front", new URL("../assets/cards/GBCP/Truffles-00.jpg", import.meta.url).href],
  ["Truffles_gbcp_back", new URL("../assets/cards/GBCP/Truffles-01.jpg", import.meta.url).href],
  ["Ulfr_gbcp_front", new URL("../assets/cards/GBCP/Ulfr-00.jpg", import.meta.url).href],
  ["Ulfr_gbcp_back", new URL("../assets/cards/GBCP/Ulfr-01.jpg", import.meta.url).href],
  ["vGutter_gbcp_front", new URL("../assets/cards/GBCP/vGutter-00.jpg", import.meta.url).href],
  ["vGutter_gbcp_back", new URL("../assets/cards/GBCP/vGutter-01.jpg", import.meta.url).href],

  /* Lamplighters in SFG style */
  ["Beacon_front", new URL("../assets/cards/Lamps_Backs/beacon.jpg", import.meta.url).href],
  ["Beacon_back", Lamps_back],
  ["Heat_front", new URL("../assets/cards/Lamps_Backs/heat.jpg", import.meta.url).href],
  ["Heat_back", Lamps_back],
  // ["Nightlight_front", new URL("../assets/cards/Lamps_Backs/nightlight.jpg", import.meta.url).href],
  ["Nightlight_front", new URL("../assets/cards/Lamps_Backs/nightlight_smallbox.jpg", import.meta.url).href],
  ["Nightlight_back", Lamps_back],
  // ["Phosphor_front", new URL("../assets/cards/Lamps_Backs/phosphor.jpg", import.meta.url).href],
  ["Phosphor_front", new URL("../assets/cards/Lamps_Backs/phosphor_smallbox.jpg", import.meta.url).href],
  ["Phosphor_back", Lamps_back],
  ["Soot_front", new URL("../assets/cards/Lamps_Backs/soot.jpg", import.meta.url).href],
  ["Soot_back", Lamps_back],
  ["Wick_front", new URL("../assets/cards/Lamps_Backs/wick.jpg", import.meta.url).href],
  ["Wick_back", Lamps_back],
]);
export default GBImages;
